/* =========================================================
   Curriculum data — 9 modules / 36 chapters (intermediate)
   ---------------------------------------------------------
   Metadata only (bilingual). Teaching content lives in
   content/<id>.<lang>.md and is fetched on the chapter page.
   ========================================================= */

const MODULES = [
  {
    id: "m1", code: "E1", zh: "时态与动词", en: "Tenses & Verbs", accent: "primary", level: 2,
    tagline: { zh: "把时态用对,句子才站得住。", en: "Get the tense right and the sentence holds." },
    description: {
      zh: "复习并深化现在、过去、完成、将来时态,以及情态动词的用法与细微差别——中级英语的地基。",
      en: "Review and deepen present, past, perfect and future tenses, plus modals — the bedrock of intermediate English.",
    },
  },
  {
    id: "m2", code: "E2", zh: "句法结构", en: "Sentence Structure", accent: "primary", level: 2,
    tagline: { zh: "从简单句到复杂句,把逻辑说清楚。", en: "From simple to complex — say what you mean clearly." },
    description: {
      zh: "复合句、条件句、被动语态、间接引语——让表达更精确、更书面、更地道。",
      en: "Complex clauses, conditionals, passive voice and reported speech — for precision and natural flow.",
    },
  },
  {
    id: "m3", code: "E3", zh: "词汇与搭配", en: "Vocabulary & Collocations", accent: "primary", level: 2,
    tagline: { zh: "单词不是孤岛,搭配才是语言。", en: "Words aren't islands; collocations are the language." },
    description: {
      zh: "构词、短语动词、同义词与语域、习语——扩大词汇量,并学会「怎么用」而不只是「什么意思」。",
      en: "Word formation, phrasal verbs, register and idioms — grow vocabulary and learn how words actually combine.",
    },
  },
  {
    id: "m4", code: "E4", zh: "阅读", en: "Reading", accent: "primary", level: 2,
    tagline: { zh: "读得快,也要读得深。", en: "Read fast — and read deep." },
    description: {
      zh: "略读寻读、推理语气、学术与新闻长文——训练在中级材料里抓主旨、辨态度、跟论证。",
      en: "Skimming, inference, academic and news texts — grasp main ideas, tone and argument in real material.",
    },
  },
  {
    id: "m5", code: "E5", zh: "写作", en: "Writing", accent: "primary", level: 3,
    tagline: { zh: "写清楚,比写漂亮更重要。", en: "Clear beats flashy every time." },
    description: {
      zh: "段落结构、议论文、正式与商务文体、修改与连贯——把想法落成可读、可说服的英文。",
      en: "Paragraphs, essays, formal and business writing, editing for coherence — turn ideas into readable English.",
    },
  },
  {
    id: "m6", code: "E6", zh: "听力", en: "Listening", accent: "primary", level: 2,
    tagline: { zh: "耳朵要适应「连起来」的英语。", en: "Train your ear for connected speech." },
    description: {
      zh: "连读弱读、讲座演讲、口音与语流、听记要点——从「听懂单词」到「听懂意思」。",
      en: "Linking, lectures, accents and note-taking — from catching words to catching meaning.",
    },
  },
  {
    id: "m7", code: "E7", zh: "口语", en: "Speaking", accent: "accent", level: 3,
    tagline: { zh: "开口说,比背一百遍管用。", en: "Speaking once beats drilling a hundred times." },
    description: {
      zh: "发音重音、流利度、讨论辩论、展示汇报——在中级阶段把「能交流」练成「敢表达」。",
      en: "Pronunciation, fluency, discussion and presentations — move from getting by to speaking up.",
    },
  },
  {
    id: "m8", code: "E8", zh: "考试与实用", en: "Exam & Practical", accent: "accent", level: 3,
    tagline: { zh: "考场之外,英语还要「能用」.", en: "Beyond exams — English has to work in real life." },
    description: {
      zh: "雅思托福策略、面试、邮件消息、文化与语用——把英语接到你的目标场景里。",
      en: "Test strategies, interviews, email, pragmatics — plug English into the situations you actually face.",
    },
  },
  {
    id: "m9", code: "E9", zh: "考研英语", en: "Kaoyan English", accent: "accent", level: 3,
    tagline: { zh: "针对考研,把英语练成分数。", en: "Turn English into a score for the grad exam." },
    description: {
      zh: "面向研究生入学考试(英语一/英语二):完形填空、阅读理解、新题型、英译汉与大小作文——按题型逐一拆解,配真题式技巧与练习。",
      en: "For China's postgraduate entrance exam (English I / II): cloze, reading, new question types, translation and essays — broken down by task with exam-style tactics and drills.",
    },
  },
  {
    id: "m10", code: "E10", zh: "寓言与短篇小说", en: "Fables & Short Stories", accent: "accent", level: 2,
    tagline: { zh: "从最短的故事开始,读懂弦外之音。", en: "Start small — short stories, big meaning." },
    description: {
      zh: "精读六篇公版短篇——伊索寓言、欧·亨利、王尔德、凯特·肖邦、莫泊桑与爱伦·坡:篇幅短、情节全,最适合练主旨、推断与反讽。",
      en: "Six public-domain short pieces — Aesop, O. Henry, Wilde, Chopin, Maupassant and Poe — short but complete, ideal for main idea, inference and irony.",
    },
  },
  {
    id: "m11", code: "E11", zh: "经典小说选段", en: "Classic Novels", accent: "primary", level: 2,
    tagline: { zh: "读名著的第一页,就上瘾。", en: "One famous first page, and you're hooked." },
    description: {
      zh: "六部经典小说的开篇或名场面——《傲慢与偏见》《圣诞颂歌》《汤姆·索亚历险记》《爱丽丝漫游奇境》《小妇人》《金银岛》:在真实文学语境里练阅读。",
      en: "Openings and set pieces from six classic novels — Pride and Prejudice, A Christmas Carol, Tom Sawyer, Alice, Little Women and Treasure Island.",
    },
  },
  {
    id: "m12", code: "E12", zh: "悬疑 · 科幻 · 哥特", en: "Mystery, Sci-Fi & Gothic", accent: "accent", level: 3,
    tagline: { zh: "跟着线索、怪物与机器读下去。", en: "Follow the clue, the monster, the machine." },
    description: {
      zh: "六篇张力十足的名作——福尔摩斯、《弗兰肯斯坦》《时间机器》《德拉库拉》《沉睡谷传奇》《黄色墙纸》:情节抓人,最练推断与氛围理解。",
      en: "Six gripping classics — Sherlock Holmes, Frankenstein, The Time Machine, Dracula, Sleepy Hollow and The Yellow Wallpaper — great for inference and atmosphere.",
    },
  },
  {
    id: "m13", code: "E13", zh: "演讲 · 散文 · 游记 · 科普", en: "Speeches, Essays & Nonfiction", accent: "primary", level: 3,
    tagline: { zh: "真实世界的声音,最见思想。", en: "Real-world voices, real ideas." },
    description: {
      zh: "六篇公版非虚构——林肯《葛底斯堡演说》、梭罗《瓦尔登湖》、爱默生《论自我》、道格拉斯自述、内莉·布莱环球报道与达尔文《贝格尔号航海记》:论说、演讲与新闻的读法。",
      en: "Six public-domain nonfiction texts — Lincoln's Gettysburg Address, Thoreau's Walden, Emerson's Self-Reliance, Douglass's Narrative, Nellie Bly's reporting and Darwin's Voyage of the Beagle.",
    },
  },
  {
    id: "m14", code: "E14", zh: "时事与真实事件", en: "News & Real Events", accent: "accent", level: 2,
    tagline: { zh: "用真实世界练完形填空。", en: "Cloze practice on the real world." },
    description: {
      zh: "以英美与世界的真实机构、地标、历史、科技、环境、商业与文体为背景的完形填空题库,共 180 道单句选词填空,做完即时判分并附解析。",
      en: "A cloze bank set against real UK/US and world institutions, history, science, environment, business and culture — 180 single-sentence items, scored with explanations.",
    },
  },
  {
    id: "m15", code: "E15", zh: "语法填空", en: "Grammar in Context", accent: "primary", level: 2,
    tagline: { zh: "在句子里把语法规则练成直觉。", en: "Turn grammar rules into instinct, in context." },
    description: {
      zh: "时态、冠词、介词、连接词、非谓语与从句/被动——180 道语法填空,凭规则选出唯一正确形式,附中英解析。",
      en: "Tenses, articles, prepositions, connectors, non-finites and clauses/passive — 180 grammar gap-fills with a single correct form and bilingual notes.",
    },
  },
  {
    id: "m16", code: "E16", zh: "词汇与搭配", en: "Vocabulary & Collocation", accent: "accent", level: 3,
    tagline: { zh: "选对那个「最自然」的词。", en: "Pick the word that simply sounds right." },
    description: {
      zh: "动名搭配、形容词与副词搭配、短语动词、易混词、固定介词与学术用词——180 道选词题,专治「意思都懂却选错」。",
      en: "Collocations, phrasal verbs, confusable words, dependent prepositions and academic word choice — 180 items for when every option looks possible.",
    },
  },
];

/* Shared metadata for the Reading Anthology chapters (E10–E13) */
const RC_OUTLINE = [
  { zh: "原文选读", en: "The passage" },
  { zh: "生词与短语", en: "Vocabulary" },
  { zh: "参考译文", en: "Reference translation" },
  { zh: "背景与理解", en: "Background & reading notes" },
  { zh: "阅读理解自测(5 题)", en: "Comprehension self-check (5 Qs)" },
];
const RC_OBJ = (first) => [
  first,
  { zh: "结合上下文猜测生词词义", en: "Guess word meaning from context" },
  { zh: "抓主旨、辨细节、做合理推断", en: "Find the main idea, details and inferences" },
  { zh: "体会语气、反讽与写作手法", en: "Feel the tone, irony and craft" },
];
const RC_OBJ_FABLE = { zh: "读懂寓言与短篇的寓意与转折", en: "Grasp the moral and twist of a short tale" };
const RC_OBJ_NOVEL = { zh: "读懂小说开篇的人物、场景与基调", en: "Read a novel's opening — character, scene and mood" };
const RC_OBJ_MYST = { zh: "跟随情节线索,读懂悬念与氛围", en: "Follow the plot; read suspense and atmosphere" };
const RC_OBJ_NONFIC = { zh: "读懂论点、论据与作者立场", en: "Grasp the claim, evidence and the author's stance" };

/* Shared metadata for the Gap-Fill / Cloze Bank chapters (E14–E16) */
const BK_OUTLINE = [
  { zh: "30 道单句完形填空", en: "30 single-sentence cloze items" },
  { zh: "上方交互作答,即时判分", en: "Answer above; scored on the spot" },
  { zh: "逐题中英文解析", en: "Per-item bilingual explanations" },
  { zh: "原创命题,取材真实话题", en: "Original items on real-world topics" },
];
const BK_OBJ = (first) => [
  first,
  { zh: "读懂空格前后的搭配与逻辑", en: "Read the collocation and logic around the blank" },
  { zh: "排除近义或形近的干扰项", en: "Eliminate near-synonym and look-alike distractors" },
  { zh: "通过自测查漏补缺", en: "Find and fix weak points by self-testing" },
];
const BK_OBJ_NEWS = { zh: "在真实话题语境中选词填空", en: "Complete blanks in real-world contexts" };
const BK_OBJ_GRAM = { zh: "依据语法规则选出唯一正确形式", en: "Choose the single correct form by grammar rules" };
const BK_OBJ_VOCAB = { zh: "辨析搭配与词义,选最自然的词", en: "Pick the most natural word by sense and collocation" };

const CHAPTERS = [
  /* ============ E1 Tenses & Verbs ============ */
  {
    id: "t1", code: "TV1", moduleId: "m1", difficulty: 2, hours: 8, prereq: [], practice: "present",
    nExamples: 5, nExercises: 6,
    title: { zh: "现在时态", en: "Present Tenses" },
    summary: { zh: "一般现在与现在进行:何时用哪种,以及常见中式错误。", en: "Present simple vs continuous: when to use which, and typical L1 mistakes." },
    objectives: [
      { zh: "区分一般现在与现在进行的用法", en: "Distinguish present simple and continuous" },
      { zh: "掌握状态动词与进行时的限制", en: "Know stative verbs and progressive restrictions" },
      { zh: "会用现在时描述习惯、事实与进行中的动作", en: "Describe habits, facts and ongoing actions" },
      { zh: "识别并改正常见时态混用", en: "Spot and fix common tense mixing" },
    ],
    outline: [
      { zh: "一般现在:习惯、事实、日程", en: "Present simple: habits, facts, schedules" },
      { zh: "现在进行:此刻、临时、变化趋势", en: "Present continuous: now, temporary, trends" },
      { zh: "状态动词列表与例外", en: "Stative verbs and exceptions" },
      { zh: "always 等进行时中的特殊含义", en: "Special meaning with always + continuous" },
      { zh: "对比练习与易错点", en: "Contrast drills and pitfalls" },
    ],
  },
  {
    id: "t2", code: "TV2", moduleId: "m1", difficulty: 2, hours: 8, prereq: ["t1"], practice: "past",
    nExamples: 5, nExercises: 6,
    title: { zh: "过去时态", en: "Past Tenses" },
    summary: { zh: "一般过去与过去进行,叙述故事与时间线。", en: "Past simple and continuous — storytelling and timelines." },
    objectives: [
      { zh: "掌握一般过去与过去进行的对比", en: "Contrast past simple and continuous" },
      { zh: "会用 when/while 连接背景与事件", en: "Use when/while for background and events" },
      { zh: "叙述经历与按时间排序", en: "Narrate experiences in sequence" },
      { zh: "避免过度使用 was/were + -ing", en: "Avoid overusing past continuous" },
    ],
    outline: [
      { zh: "一般过去:完成动作与时间点", en: "Past simple: completed actions" },
      { zh: "过去进行:背景与被打断的动作", en: "Past continuous: background and interruption" },
      { zh: "时间连接词 when / while / as", en: "When / while / as" },
      { zh: "叙述技巧与段落组织", en: "Narration and paragraph flow" },
      { zh: "不规则动词复习策略", en: "Irregular verb review strategies" },
    ],
  },
  {
    id: "t3", code: "TV3", moduleId: "m1", difficulty: 3, hours: 10, prereq: ["t2"], practice: "perfect",
    nExamples: 5, nExercises: 6,
    title: { zh: "完成时态", en: "Perfect Tenses" },
    summary: { zh: "现在完成与过去完成:经验、结果、先后顺序。", en: "Present and past perfect: experience, results and sequence." },
    objectives: [
      { zh: "理解「与现在有联系」的完成时", en: "Grasp the link to now in perfect tenses" },
      { zh: "掌握 for/since/already/yet/just", en: "Use for, since, already, yet, just" },
      { zh: "会用过去完成表示「过去的过去」", en: "Use past perfect for earlier past" },
      { zh: "区分英式美式对现在完成的用法差异", en: "Note BrE/AmE differences with present perfect" },
    ],
    outline: [
      { zh: "现在完成:经验、结果、未完成", en: "Present perfect: experience, result, unfinished" },
      { zh: "for / since / 时间段", en: "For / since / time periods" },
      { zh: "过去完成与时间轴", en: "Past perfect on a timeline" },
      { zh: "与简单过去的选用", en: "Choosing perfect vs simple past" },
      { zh: "常见错误与修正", en: "Common errors and fixes" },
    ],
  },
  {
    id: "t4", code: "TV4", moduleId: "m1", difficulty: 3, hours: 9, prereq: ["t3"], practice: "modals",
    nExamples: 5, nExercises: 6,
    title: { zh: "将来时与情态", en: "Future & Modals" },
    summary: { zh: "will/be going to/现在进行表将来,以及 can/must/should 等。", en: "Future forms and modals: will, going to, can, must, should and more." },
    objectives: [
      { zh: "比较 will / be going to / present for future", en: "Compare future forms" },
      { zh: "掌握主要情态动词的语气与否定", en: "Master modals for ability, obligation, advice" },
      { zh: "理解 must vs have to / should vs ought to", en: "Distinguish near-synonymous modals" },
      { zh: "在正式与非正式语境中选词", en: "Choose modals by register" },
    ],
    outline: [
      { zh: "将来时的三种常见表达", en: "Three common future forms" },
      { zh: "情态:能力、许可、义务、推测", en: "Modals: ability, permission, obligation, deduction" },
      { zh: "半情态 have to / need to", en: "Semi-modals" },
      { zh: "委婉建议与拒绝", en: "Soft suggestions and refusals" },
      { zh: "写作与口语中的语气选择", en: "Tone in writing and speech" },
    ],
  },

  /* ============ E2 Sentence Structure ============ */
  {
    id: "s1", code: "SS1", moduleId: "m2", difficulty: 2, hours: 9, prereq: ["t1"], practice: "clauses",
    nExamples: 5, nExercises: 6,
    title: { zh: "复合句与从句", en: "Complex Sentences & Clauses" },
    summary: { zh: "名词、形容词、副词从句——把短句扩展成有层次的句子。", en: "Noun, adjective and adverb clauses — expand simple sentences with structure." },
    objectives: [
      { zh: "识别三种从句的功能", en: "Identify three clause types" },
      { zh: "掌握关系代词与关系副词", en: "Use relative pronouns and adverbs" },
      { zh: "会用 that/whether/if 引导名词从句", en: "Lead noun clauses with that/whether/if" },
      { zh: "避免 run-on 与 comma splice", en: "Avoid run-ons and comma splices" },
    ],
    outline: [
      { zh: "独立句与从句", en: "Independent and dependent clauses" },
      { zh: "定语从句:限定与非限定", en: "Relative clauses: defining and non-defining" },
      { zh: "名词从句作主语/宾语", en: "Noun clauses as subjects/objects" },
      { zh: "状语从句:时间、原因、让步", en: "Adverb clauses: time, reason, concession" },
      { zh: "标点与从句位置", en: "Punctuation and clause position" },
    ],
  },
  {
    id: "s2", code: "SS2", moduleId: "m2", difficulty: 2, hours: 8, prereq: ["s1"], practice: "conditionals",
    nExamples: 5, nExercises: 6,
    title: { zh: "条件句", en: "Conditionals" },
    summary: { zh: "零到第三类条件句,以及 unless / as long as 等变体。", en: "Zero through third conditionals, plus unless and as long as." },
    objectives: [
      { zh: "掌握四类条件句的形式与意义", en: "Master four conditional types" },
      { zh: "区分真实与虚拟条件", en: "Separate real and unreal conditions" },
      { zh: "会用混合条件与倒装 if", en: "Use mixed conditionals and inverted if" },
      { zh: "在写作中表达建议与假设", en: "Express advice and hypotheticals in writing" },
    ],
    outline: [
      { zh: "零条件与第一条件", en: "Zero and first conditional" },
      { zh: "第二条件:与现在/将来相反", en: "Second conditional: unreal present/future" },
      { zh: "第三条件:与过去相反", en: "Third conditional: unreal past" },
      { zh: "混合条件与 unless", en: "Mixed conditionals and unless" },
      { zh: "wish / if only 相关表达", en: "Wish and if only" },
    ],
  },
  {
    id: "s3", code: "SS3", moduleId: "m2", difficulty: 2, hours: 8, prereq: ["t2"], practice: "passive",
    nExamples: 5, nExercises: 6,
    title: { zh: "被动语态", en: "Passive Voice" },
    summary: { zh: "各时态的被动形式,以及何时「该用被动」.", en: "Passive in every tense — and when it actually helps." },
    objectives: [
      { zh: "构成各时态的被动式", en: "Form passive in major tenses" },
      { zh: "理解施事者省略与 by-phrase", en: "Omit agent vs use by-phrase" },
      { zh: "掌握 get-passive 与感官被动", en: "Know get-passive and sensory passives" },
      { zh: "在学术与新闻文体中选用被动", en: "Use passive in academic and news style" },
    ],
    outline: [
      { zh: "被动基本结构 be + past participle", en: "Basic passive structure" },
      { zh: "各时态被动对照表", en: "Passive across tenses" },
      { zh: "不及物动词与无被动", en: "Intransitives: no passive" },
      { zh: "主动 vs 被动的语用选择", en: "Pragmatic choice: active vs passive" },
      { zh: "常见错误:及物动词遗漏宾语", en: "Errors: missing object with transitive verbs" },
    ],
  },
  {
    id: "s4", code: "SS4", moduleId: "m2", difficulty: 3, hours: 8, prereq: ["s1", "t2"], practice: "reported",
    nExamples: 5, nExercises: 6,
    title: { zh: "间接引语", en: "Reported Speech" },
    summary: { zh: "转述陈述、疑问与祈使,以及时态后退规则。", en: "Report statements, questions and commands — backshift and exceptions." },
    objectives: [
      { zh: "掌握 say/tell/ask 的用法区别", en: "Distinguish say, tell and ask" },
      { zh: "应用时态后退与时间词变化", en: "Apply backshift and time-word shifts" },
      { zh: "转述疑问句与祈使句", en: "Report questions and imperatives" },
      { zh: "识别不必后退的例外情况", en: "Know when backshift isn't required" },
    ],
    outline: [
      { zh: "直接引语 vs 间接引语", en: "Direct vs reported speech" },
      { zh: "时态后退规则", en: "Backshift rules" },
      { zh: "转述疑问:语序变化", en: "Reporting questions: word order" },
      { zh: "转述建议、命令、请求", en: "Reporting suggestions and orders" },
      { zh: "新闻报道中的引述", en: "Reporting in news writing" },
    ],
  },

  /* ============ E3 Vocabulary ============ */
  {
    id: "v1", code: "VX1", moduleId: "m3", difficulty: 2, hours: 7, prereq: [], practice: "wordform",
    nExamples: 5, nExercises: 6,
    title: { zh: "构词法", en: "Word Formation" },
    summary: { zh: "前缀、后缀、词根——见词猜义,扩大词汇网。", en: "Prefixes, suffixes and roots — guess meaning and grow your network." },
    objectives: [
      { zh: "识别常见前缀与后缀", en: "Recognize common affixes" },
      { zh: "区分词性转换(-tion/-ment/-ize)", en: "Convert word class with suffixes" },
      { zh: "用构词法记一批学术词汇", en: "Learn academic words via formation" },
      { zh: "避免「假朋友」式猜词", en: "Avoid false friends when guessing" },
    ],
    outline: [
      { zh: "前缀:否定与程度", en: "Prefixes: negation and degree" },
      { zh: "名词/形容词/动词后缀", en: "Noun, adjective, verb suffixes" },
      { zh: "复合词与合成", en: "Compounds" },
      { zh: "词根与同源词", en: "Roots and cognates" },
      { zh: "词汇笔记本方法", en: "Vocabulary notebook method" },
    ],
  },
  {
    id: "v2", code: "VX2", moduleId: "m3", difficulty: 2, hours: 10, prereq: ["v1"], practice: "phrasal",
    nExamples: 5, nExercises: 6,
    title: { zh: "短语动词与搭配", en: "Phrasal Verbs & Collocations" },
    summary: { zh: "look up, give up, take off…以及 make a decision 类固定搭配。", en: "Phrasal verbs and strong collocations like make a decision." },
    objectives: [
      { zh: "理解短语动词的及物/不及物与可分性", en: "Transitive/intransitive and separable phrasals" },
      { zh: "掌握高频短语动词一批", en: "Master a core set of phrasal verbs" },
      { zh: "学会查搭配词典与语料", en: "Use collocation dictionaries and corpora" },
      { zh: "在口语中自然使用短语动词", en: "Use phrasals naturally in speech" },
    ],
    outline: [
      { zh: "短语动词结构", en: "Structure of phrasal verbs" },
      { zh: "字面义 vs 引申义", en: "Literal vs idiomatic meaning" },
      { zh: "强搭配:动词+名词", en: "Strong verb + noun collocations" },
      { zh: "形容词+名词搭配", en: "Adjective + noun collocations" },
      { zh: "主题词汇簇(工作/学习)", en: "Topic-based word clusters" },
    ],
  },
  {
    id: "v3", code: "VX3", moduleId: "m3", difficulty: 3, hours: 8, prereq: ["v2"], practice: "register",
    nExamples: 5, nExercises: 6,
    title: { zh: "同义词与语域", en: "Synonyms & Register" },
    summary: { zh: "big/large/great, ask/request/inquire——近义不同用。", en: "Near-synonyms differ: ask vs request vs inquire." },
    objectives: [
      { zh: "区分正式/中性/非正式用词", en: "Distinguish formal, neutral, informal" },
      { zh: "选用同义词时注意搭配限制", en: "Respect collocation with synonyms" },
      { zh: "在邮件与论文中选 appropriate 词汇", en: "Choose words for email vs essays" },
      { zh: "用语料库验证搭配", en: "Verify with corpus examples" },
    ],
    outline: [
      { zh: "语域:spoken vs written", en: "Register: spoken vs written" },
      { zh: "同义词辨析方法", en: "How to compare synonyms" },
      { zh: "学术词汇 AWL 入门", en: "Academic Word List intro" },
      { zh: "避免堆砌「大词」", en: "Avoid pompous word stacking" },
      { zh: "改写练习:升降正式度", en: "Rewriting for register shift" },
    ],
  },
  {
    id: "v4", code: "VX4", moduleId: "m3", difficulty: 3, hours: 8, prereq: ["v2"], practice: "idioms",
    nExamples: 5, nExercises: 6,
    title: { zh: "习语与固定表达", en: "Idioms & Fixed Expressions" },
    summary: { zh: "break the ice, piece of cake——理解文化,别逐字翻译。", en: "Idioms like break the ice — culture, not word-for-word." },
    objectives: [
      { zh: "理解习语的整体意义", en: "Grasp idioms as chunks" },
      { zh: "掌握常见主题习语一批", en: "Learn themed idioms" },
      { zh: "区分可用与过时的表达", en: "Spot dated vs current idioms" },
      { zh: "在合适场合使用,避免过度", en: "Use idioms sparingly and appropriately" },
    ],
    outline: [
      { zh: "习语 vs 字面短语", en: "Idioms vs literal phrases" },
      { zh: "隐喻与来源", en: "Metaphor and origin" },
      { zh: "商务与日常习语", en: "Business and everyday idioms" },
      { zh: "固定搭配句型", en: "Fixed sentence frames" },
      { zh: "跨文化误读警示", en: "Cross-cultural pitfalls" },
    ],
  },

  /* ============ E4 Reading ============ */
  {
    id: "r1", code: "RD1", moduleId: "m4", difficulty: 2, hours: 8, prereq: ["v2"], practice: "reading",
    nExamples: 5, nExercises: 6,
    title: { zh: "略读与寻读", en: "Skimming & Scanning" },
    summary: { zh: "快速抓主旨、定位细节——阅读不是每个词都读。", en: "Grab the gist and find details — you don't read every word." },
    objectives: [
      { zh: "会用标题/首段预测内容", en: "Predict from titles and openings" },
      { zh: "略读抓主旨与结构", en: "Skim for gist and structure" },
      { zh: "寻读定位数字、名字、日期", en: "Scan for numbers, names, dates" },
      { zh: "制定考试时间分配策略", en: "Plan time in timed reading" },
    ],
    outline: [
      { zh: "阅读目的决定读法", en: "Purpose drives method" },
      { zh: "略读三步法", en: "Three-step skimming" },
      { zh: "寻读信号词", en: "Scanning cues" },
      { zh: "段落主题句", en: "Topic sentences" },
      { zh: "练习:新闻与说明文", en: "Practice: news and expository texts" },
    ],
  },
  {
    id: "r2", code: "RD2", moduleId: "m4", difficulty: 2, hours: 9, prereq: ["r1"], practice: "inference",
    nExamples: 5, nExercises: 6,
    title: { zh: "推理与语气", en: "Inference & Tone" },
    summary: { zh: "作者没明说的意思,以及态度是支持还是讽刺。", en: "What the author implies — and whether they're sincere or ironic." },
    objectives: [
      { zh: "从上下文推断生词义", en: "Infer word meaning from context" },
      { zh: "识别作者态度与立场", en: "Identify attitude and stance" },
      { zh: "理解讽刺与隐含批评", en: "Read irony and implicit criticism" },
      { zh: "区分 fact vs opinion", en: "Separate fact from opinion" },
    ],
    outline: [
      { zh: "语境猜词", en: "Context clues" },
      { zh: "态度词与评价语言", en: "Attitude markers" },
      { zh: "推理题常见类型", en: "Inference question types" },
      { zh: "语气: formal / neutral / critical", en: "Tone labels" },
      { zh: "评论文精读一篇", en: "Close read one opinion piece" },
    ],
  },
  {
    id: "r3", code: "RD3", moduleId: "m4", difficulty: 3, hours: 10, prereq: ["r2", "s1"], practice: "academic",
    nExamples: 5, nExercises: 6,
    title: { zh: "学术阅读", en: "Academic Reading" },
    summary: { zh: "论文摘要、教科书章节——跟论证,不跟生词跑。", en: "Abstracts and textbook chapters — follow the argument, not every unknown word." },
    objectives: [
      { zh: "读懂 IMRaD 结构", en: "Navigate IMRaD structure" },
      { zh: "识别 thesis 与 supporting claims", en: "Find thesis and support" },
      { zh: "处理长句与嵌入从句", en: "Parse long embedded clauses" },
      { zh: "做结构化读书笔记", en: "Take structured reading notes" },
    ],
    outline: [
      { zh: "学术文本特征", en: "Features of academic texts" },
      { zh: "摘要阅读法", en: "Reading abstracts" },
      { zh: "论证图式", en: "Argument mapping" },
      { zh: "引用与转述识别", en: "Spot citations and paraphrase" },
      { zh: "略读整章策略", en: "Skimming a full chapter" },
    ],
  },
  {
    id: "r4", code: "RD4", moduleId: "m4", difficulty: 3, hours: 9, prereq: ["r2"], practice: "news",
    nExamples: 5, nExercises: 6,
    title: { zh: "新闻与长文", en: "News & Long-form" },
    summary: { zh: "倒金字塔、特写与专栏——不同体裁,不同读法。", en: "Inverted pyramid, features and columns — genre shapes reading." },
    objectives: [
      { zh: "适应新闻导语结构", en: "Handle news lead structure" },
      { zh: "比较长文与短消息", en: "Compare long-form vs brief news" },
      { zh: "跨文化新闻用语", en: "Cross-cultural news language" },
      { zh: "建立可持续的外刊习惯", en: "Build a sustainable reading habit" },
    ],
    outline: [
      { zh: "倒金字塔", en: "Inverted pyramid" },
      { zh: "特写与人物稿", en: "Features and profiles" },
      { zh: "专栏与评论", en: "Columns and op-eds" },
      { zh: "假新闻与来源核查", en: "Fake news and source checking" },
      { zh: "推荐阅读清单", en: "Suggested reading list" },
    ],
  },

  /* ============ E5 Writing ============ */
  {
    id: "w1", code: "WR1", moduleId: "m5", difficulty: 2, hours: 8, prereq: ["s1"], practice: "paragraph",
    nExamples: 5, nExercises: 6,
    title: { zh: "段落结构", en: "Paragraph Structure" },
    summary: { zh: "主题句、展开、例证、小结——一段只讲一个中心。", en: "Topic sentence, development, example, wrap — one main idea per paragraph." },
    objectives: [
      { zh: "写出清晰主题句", en: "Write clear topic sentences" },
      { zh: "用例证与解释展开", en: "Develop with examples and explanation" },
      { zh: "使用连接词体现逻辑", en: "Use linkers for logic" },
      { zh: "避免中式段落布局", en: "Avoid L1 paragraph patterns" },
    ],
    outline: [
      { zh: "TEEL / PEEL 结构", en: "TEEL / PEEL structure" },
      { zh: "统一性与连贯性", en: "Unity and coherence" },
      { zh: "连接词分类", en: "Linkers by function" },
      { zh: "段落长度与节奏", en: "Paragraph length and rhythm" },
      { zh: "修改 checklist", en: "Revision checklist" },
    ],
  },
  {
    id: "w2", code: "WR2", moduleId: "m5", difficulty: 3, hours: 10, prereq: ["w1", "s2"], practice: "essay",
    nExamples: 5, nExercises: 6,
    title: { zh: "议论文", en: "Argumentative Essays" },
    summary: { zh: "立场、论据、反驳——像辩论一样写。", en: "Claim, evidence, counterargument — write like you debate." },
    objectives: [
      { zh: "提出明确 thesis", en: "State a clear thesis" },
      { zh: "组织 body 与反驳段", en: "Structure body and rebuttal" },
      { zh: "避免 logical fallacies", en: "Avoid logical fallacies" },
      { zh: "写结论而不重复开头", en: "Conclude without repeating the intro" },
    ],
    outline: [
      { zh: "议论文 vs 说明文", en: "Argument vs exposition" },
      { zh: "引言 hook 与 thesis", en: "Intro hook and thesis" },
      { zh: "主体段论证", en: "Body argumentation" },
      { zh: "处理 counterargument", en: "Handling counterarguments" },
      { zh: "雅思/托福 Task 2 框架", en: "IELTS/TOEFL Task 2 frame" },
    ],
  },
  {
    id: "w3", code: "WR3", moduleId: "m5", difficulty: 3, hours: 9, prereq: ["w1", "v3"], practice: "business",
    nExamples: 5, nExercises: 6,
    title: { zh: "正式与商务写作", en: "Formal & Business Writing" },
    summary: { zh: "邮件、报告、备忘录——语气礼貌,信息清楚。", en: "Email, reports, memos — polite tone, clear information." },
    objectives: [
      { zh: "掌握商务邮件结构", en: "Master business email structure" },
      { zh: "选用正式称呼与结尾", en: "Choose formal openings and closings" },
      { zh: "写清楚 purpose 与 action items", en: "State purpose and action items" },
      { zh: "避免过于直接或模糊", en: "Avoid blunt or vague wording" },
    ],
    outline: [
      { zh: "邮件组成部分", en: "Email components" },
      { zh: "请求、道歉、跟进", en: "Requests, apologies, follow-ups" },
      { zh: "报告与摘要", en: "Reports and summaries" },
      { zh: "语气: direct vs indirect cultures", en: "Direct vs indirect cultures" },
      { zh: "模板与个性化平衡", en: "Templates vs personalization" },
    ],
  },
  {
    id: "w4", code: "WR4", moduleId: "m5", difficulty: 3, hours: 8, prereq: ["w2"], practice: "editing",
    nExamples: 5, nExercises: 6,
    title: { zh: "修改与连贯", en: "Editing & Coherence" },
    summary: { zh: "自己当编辑:删冗余,补连接,统一时态与人称。", en: "Be your own editor: cut fluff, add links, unify tense and voice." },
    objectives: [
      { zh: "分层修改:内容/结构/语言", en: "Revise in layers: content, structure, language" },
      { zh: "检查指代与重复", en: "Check reference and repetition" },
      { zh: "朗读法找拗口句", en: "Read aloud for awkwardness" },
      { zh: "使用校对工具但不盲信", en: "Use tools but don't trust blindly" },
    ],
    outline: [
      { zh: "修改流程", en: "Revision workflow" },
      { zh: "连贯:代词与替换", en: "Coherence: pronouns and substitution" },
      { zh: "简洁:砍掉冗余", en: "Concision: cut redundancy" },
      { zh: "语法与标点终审", en: "Final grammar and punctuation pass" },
      { zh: "同伴互改方法", en: "Peer review method" },
    ],
  },

  /* ============ E6 Listening ============ */
  {
    id: "l1", code: "LS1", moduleId: "m6", difficulty: 2, hours: 8, prereq: ["t1"], practice: "listening",
    nExamples: 5, nExercises: 6,
    title: { zh: "连读与弱读", en: "Connected Speech" },
    summary: { zh: "连读、省音、弱读——词典发音和真实口语不一样。", en: "Linking, elision, weak forms — real speech isn't dictionary speech." },
    objectives: [
      { zh: "识别常见连读模式", en: "Recognize linking patterns" },
      { zh: "掌握功能词弱读", en: "Know weak forms of function words" },
      { zh: "听写练耳朵分辨音素", en: "Use dictation for phoneme discrimination" },
      { zh: "适应自然语速材料", en: "Adapt to natural-speed audio" },
    ],
    outline: [
      { zh: "连读规则入门", en: "Linking rules intro" },
      { zh: "弱读: of / to / and", en: "Weak forms" },
      { zh: "省音与同化", en: "Elision and assimilation" },
      { zh: "听力材料分级", en: "Graded listening materials" },
      { zh: "跟读 shadowing 练习", en: "Shadowing practice" },
    ],
  },
  {
    id: "l2", code: "LS2", moduleId: "m6", difficulty: 2, hours: 9, prereq: ["l1"], practice: "lectures",
    nExamples: 5, nExercises: 6,
    title: { zh: "讲座与演讲", en: "Lectures & Talks" },
    summary: { zh: "信号词、结构词、重读——听清「要点在哪」.", en: "Signposting and stress — hear where the point is." },
    objectives: [
      { zh: "识别讲座结构信号", en: "Catch lecture signposts" },
      { zh: "区分例子与核心观点", en: "Separate examples from main points" },
      { zh: "应对口音与背景噪音", en: "Handle accent and noise" },
      { zh: "预览幻灯片辅助理解", en: "Use slides to support comprehension" },
    ],
    outline: [
      { zh: "讲座开场与 roadmap", en: "Lecture openings and roadmaps" },
      { zh: "列举与对比信号词", en: "Listing and contrast markers" },
      { zh: "TED 式演讲特点", en: "TED-style talk features" },
      { zh: "听前预测", en: "Pre-listening prediction" },
      { zh: "听后自检", en: "Post-listening self-check" },
    ],
  },
  {
    id: "l3", code: "LS3", moduleId: "m6", difficulty: 3, hours: 9, prereq: ["l1"], practice: "accents",
    nExamples: 5, nExercises: 6,
    title: { zh: "口音与语流", en: "Accents & Fast Speech" },
    summary: { zh: "英音、美音、澳音——变体多,但规律仍可学。", en: "BrE, AmE, AusE — variants abound, patterns still learnable." },
    objectives: [
      { zh: "了解主要 accent 差异", en: "Know major accent differences" },
      { zh: "在快语流中抓关键词", en: "Catch keywords in fast speech" },
      { zh: "减少「听懂每个词」执念", en: "Let go of catching every word" },
      { zh: "多口音 exposure 计划", en: "Plan multi-accent exposure" },
    ],
    outline: [
      { zh: "rhotic vs non-rhotic", en: "Rhotic vs non-rhotic" },
      { zh: "元音差异举例", en: "Vowel differences" },
      { zh: "语流中的信息层次", en: "Information hierarchy in speech" },
      { zh: "播客与访谈推荐", en: "Podcast and interview picks" },
      { zh: "自适应策略", en: "Adaptation strategies" },
    ],
  },
  {
    id: "l4", code: "LS4", moduleId: "m6", difficulty: 3, hours: 8, prereq: ["l2"], practice: "notetaking",
    nExamples: 5, nExercises: 6,
    title: { zh: "听记要点", en: "Note-taking While Listening" },
    summary: { zh: "缩写、符号、分层记录——听的同时留痕迹。", en: "Abbreviations, symbols, layers — leave a trail while you listen." },
    objectives: [
      { zh: "建立个人缩写系统", en: "Build a personal shorthand" },
      { zh: "区分记录 vs 听", en: "Balance noting vs listening" },
      { zh: "用笔记支持听后复述", en: "Use notes for retelling" },
      { zh: "考试场景时间分配", en: "Time management in tests" },
    ],
    outline: [
      { zh: "Cornell 笔记法", en: "Cornell note method" },
      { zh: "只记关键词", en: "Keywords only" },
      { zh: "符号系统", en: "Symbol system" },
      { zh: "听后整理", en: "Post-listening cleanup" },
      { zh: "模拟考试练习", en: "Mock test practice" },
    ],
  },

  /* ============ E7 Speaking ============ */
  {
    id: "p1", code: "SP1", moduleId: "m7", difficulty: 2, hours: 8, prereq: ["l1"], practice: "pronunciation",
    nExamples: 5, nExercises: 6,
    title: { zh: "发音与重音", en: "Pronunciation & Stress" },
    summary: { zh: "音标、单词重音、句重音——让人听得懂你在说什么。", en: "Phonetics, word and sentence stress — be understood." },
    objectives: [
      { zh: "使用 IPA 查发音", en: "Use IPA in dictionaries" },
      { zh: "掌握单词重音规则", en: "Apply word stress rules" },
      { zh: "练习句重音与节奏", en: "Practice sentence stress and rhythm" },
      { zh: "录音对比自我纠正", en: "Record and compare for self-correction" },
    ],
    outline: [
      { zh: "IPA 入门", en: "IPA intro" },
      { zh: "元音对比练习", en: "Vowel contrast drills" },
      { zh: "辅音难点: th / v / r", en: "Consonant trouble spots" },
      { zh: "重音决定词性", en: "Stress shifts meaning (noun/verb)" },
      { zh: "节奏与 chunking", en: "Rhythm and chunking" },
    ],
  },
  {
    id: "p2", code: "SP2", moduleId: "m7", difficulty: 2, hours: 8, prereq: ["p1"], practice: "fluency",
    nExamples: 5, nExercises: 6,
    title: { zh: "流利度", en: "Fluency" },
    summary: { zh: "填充词、停顿、自我修正——流利不是完美。", en: "Fillers, pauses, self-repair — fluency isn't perfection." },
    objectives: [
      { zh: "减少不当停顿与沉默", en: "Reduce awkward pauses" },
      { zh: "自然使用 well / you know", en: "Use fillers naturally" },
      { zh: "学会 paraphrase 绕开生词", en: "Paraphrase around unknown words" },
      { zh: "延长回答而非单字回复", en: "Extend answers beyond one word" },
    ],
    outline: [
      { zh: "流利 vs 准确", en: "Fluency vs accuracy" },
      { zh: "填充与话语标记", en: "Fillers and discourse markers" },
      { zh: "自我修正策略", en: "Self-correction strategies" },
      { zh: "话题扩展技巧", en: "Extending topics" },
      { zh: "日常口语任务", en: "Everyday speaking tasks" },
    ],
  },
  {
    id: "p3", code: "SP3", moduleId: "m7", difficulty: 3, hours: 9, prereq: ["p2", "s2"], practice: "debate",
    nExamples: 5, nExercises: 6,
    title: { zh: "讨论与辩论", en: "Discussion & Debate" },
    summary: { zh: "表达观点、同意反对、举例反驳——对话不是独白。", en: "Agree, disagree, support, rebut — conversation isn't a monologue." },
    objectives: [
      { zh: "礼貌表达不同意见", en: "Disagree politely" },
      { zh: "用例子支撑观点", en: "Support views with examples" },
      { zh: "总结他人观点再回应", en: "Summarize then respond" },
      { zh: "控制话轮不垄断", en: "Share the floor" },
    ],
    outline: [
      { zh: "观点表达句型", en: "Opinion frames" },
      { zh: "同意与部分同意", en: "Agree and partial agree" },
      { zh: "反驳与让步", en: "Rebuttal and concession" },
      { zh: "小组讨论角色", en: "Roles in group discussion" },
      { zh: "辩论赛基本结构", en: "Basic debate structure" },
    ],
  },
  {
    id: "p4", code: "SP4", moduleId: "m7", difficulty: 3, hours: 10, prereq: ["p2", "w1"], practice: "presentation",
    nExamples: 5, nExercises: 6,
    title: { zh: "展示与汇报", en: "Presentations" },
    summary: { zh: "开场、主体、Q&A——把一页页要点说成故事。", en: "Opening, body, Q&A — turn bullet points into a story." },
    objectives: [
      { zh: "设计清晰 presentation 结构", en: "Structure a presentation clearly" },
      { zh: "使用视觉辅助而非念稿", en: "Use visuals, don't read slides" },
      { zh: "处理提问与未知问题", en: "Handle Q&A and unknowns" },
      { zh: "控制语速与 eye contact", en: "Manage pace and eye contact" },
    ],
    outline: [
      { zh: "开场 hook", en: "Opening hook" },
      { zh: "主体 signposting", en: "Body signposting" },
      { zh: "图表描述语言", en: "Describing charts" },
      { zh: "结尾与 call to action", en: "Closing and call to action" },
      { zh: "彩排 checklist", en: "Rehearsal checklist" },
    ],
  },

  /* ============ E8 Exam & Practical ============ */
  {
    id: "x1", code: "XP1", moduleId: "m8", difficulty: 3, hours: 10, prereq: ["r2", "w2"], practice: "ieltstoefl",
    nExamples: 5, nExercises: 6,
    title: { zh: "雅思与托福策略", en: "IELTS & TOEFL Strategies" },
    summary: { zh: "四科题型、评分逻辑、备考节奏——考试是项目,不是碰运气。", en: "Four skills, scoring logic, study rhythm — exams are projects, not luck." },
    objectives: [
      { zh: "了解两类考试结构差异", en: "Compare IELTS and TOEFL formats" },
      { zh: "制定分科备考计划", en: "Plan prep by skill" },
      { zh: "识别各题型时间陷阱", en: "Spot time traps per question type" },
      { zh: "用真题而非只刷技巧", en: "Use real tests, not tricks alone" },
    ],
    outline: [
      { zh: "考试对比总览", en: "Exam comparison overview" },
      { zh: "阅读/听力题型地图", en: "Reading/listening question maps" },
      { zh: "写作评分标准解读", en: "Writing rubrics decoded" },
      { zh: "口语评分维度", en: "Speaking assessment criteria" },
      { zh: "8 周备考表示例", en: "Sample 8-week schedule" },
    ],
  },
  {
    id: "x2", code: "XP2", moduleId: "m8", difficulty: 3, hours: 8, prereq: ["p2", "w3"], practice: "interview",
    nExamples: 5, nExercises: 6,
    title: { zh: "面试英语", en: "Interview English" },
    summary: { zh: "自我介绍、STAR 答法、薪资与反问——职场第一印象。", en: "Intro, STAR answers, salary and questions — first impressions at work." },
    objectives: [
      { zh: "准备 1/3 分钟自我介绍", en: "Prepare 1- and 3-minute intros" },
      { zh: "用 STAR 回答行为题", en: "Answer behavioral questions with STAR" },
      { zh: "描述优势而不自夸过头", en: "State strengths without boasting" },
      { zh: "准备 thoughtful 反问", en: "Prepare thoughtful questions back" },
    ],
    outline: [
      { zh: "面试流程与语言", en: "Interview flow and language" },
      { zh: "常见问题的英文框架", en: "Frames for common questions" },
      { zh: "弱点题怎么答", en: "Answering weakness questions" },
      { zh: "视频面试注意点", en: "Video interview tips" },
      { zh: "跟进 thank-you email", en: "Thank-you follow-up email" },
    ],
  },
  {
    id: "x3", code: "XP3", moduleId: "m8", difficulty: 2, hours: 7, prereq: ["w3"], practice: "emailmsg",
    nExamples: 5, nExercises: 6,
    title: { zh: "邮件与消息", en: "Email & Messaging" },
    summary: { zh: "Subject line、礼貌程度、表情符号边界——频道不同,规矩不同。", en: "Subject lines, politeness, emoji boundaries — channel matters." },
    objectives: [
      { zh: "写清晰 subject 与首句", en: "Write clear subjects and openings" },
      { zh: "区分 email / chat / 社交媒体", en: "Separate email, chat and social" },
      { zh: "跟进与催办不失礼", en: "Follow up politely" },
      { zh: "跨时区沟通", en: "Cross-time-zone communication" },
    ],
    outline: [
      { zh: "邮件礼仪", en: "Email etiquette" },
      { zh: "即时消息特点", en: "Instant messaging norms" },
      { zh: "附件与抄送", en: "Attachments and CC" },
      { zh: "常见模板", en: "Common templates" },
      { zh: "文化差异案例", en: "Cross-cultural cases" },
    ],
  },
  {
    id: "x4", code: "XP4", moduleId: "m8", difficulty: 3, hours: 8, prereq: ["v4", "p3"], practice: "pragmatics",
    nExamples: 5, nExercises: 6,
    title: { zh: "文化与语用", en: "Culture & Pragmatics" },
    summary: { zh: "礼貌、幽默、禁忌——说得对,还要说得体。", en: "Politeness, humor, taboos — correct isn't always appropriate." },
    objectives: [
      { zh: "理解 directness 文化差异", en: "Understand directness across cultures" },
      { zh: "识别语用失败案例", en: "Spot pragmatic failure" },
      { zh: "在多元环境中调整表达", en: "Adjust in multicultural settings" },
      { zh: "建立跨文化观察习惯", en: "Build cross-cultural observation habits" },
    ],
    outline: [
      { zh: "礼貌理论入门", en: "Politeness theory intro" },
      { zh: "请求与拒绝的间接性", en: "Indirect requests and refusals" },
      { zh: "幽默与讽刺风险", en: "Humor and irony risks" },
      { zh: "身体语言与副语言", en: "Body language and paralanguage" },
      { zh: "案例讨论", en: "Case discussions" },
    ],
  },
  {
    id: "x5", code: "XP5", moduleId: "m8", difficulty: 2, hours: 6, prereq: ["p2"], practice: "travel",
    nExamples: 3, nExercises: 4,
    title: { zh: "旅行英语", en: "Travel English" },
    summary: { zh: "值机、入住、问路、打车——在路上把英语用起来。", en: "Airports, hotels, directions, taxis — English on the move." },
    objectives: [
      { zh: "在机场与酒店完成常见办理", en: "Handle airport and hotel check-in" },
      { zh: "自然地问路与听懂指路", en: "Ask for and follow directions naturally" },
      { zh: "用委婉句型提出请求(换房、加床等)", en: "Make polite requests (room change, extras)" },
      { zh: "应对延误、丢失、退改等突发", en: "Cope with delays, lost items and changes" },
    ],
    outline: [
      { zh: "机场值机与安检用语", en: "Airport check-in and security" },
      { zh: "酒店入住与退房", en: "Hotel check-in and check-out" },
      { zh: "问路与公共交通", en: "Directions and public transport" },
      { zh: "打车与网约车", en: "Taxis and ride-hailing" },
      { zh: "突发情况求助", en: "Asking for help when things go wrong" },
    ],
  },
  {
    id: "x6", code: "XP6", moduleId: "m8", difficulty: 1, hours: 5, prereq: ["p2"], practice: "dining",
    nExamples: 3, nExercises: 4,
    title: { zh: "点餐与用餐", en: "Dining & Ordering" },
    summary: { zh: "点单、加料、买单、投诉——餐厅与咖啡店里的地道口语。", en: "Ordering, customizing, paying, complaints — natural café and restaurant English." },
    objectives: [
      { zh: "在餐厅与咖啡店自如点单", en: "Order confidently in restaurants and cafés" },
      { zh: "说明忌口、加料与做法要求", en: "State allergies, add-ons and preferences" },
      { zh: "区分堂食/外带与买单表达", en: "Distinguish for-here/to-go and paying" },
      { zh: "礼貌处理上错菜或问题", en: "Politely handle mistakes with an order" },
    ],
    outline: [
      { zh: "入座与看菜单", en: "Being seated and reading the menu" },
      { zh: "点单常用句型", en: "Core ordering phrases" },
      { zh: "忌口、加料与定制", en: "Allergies, add-ons and customizing" },
      { zh: "堂食、外带与买单", en: "For here, to go, and the bill" },
      { zh: "退换与礼貌投诉", en: "Sending back and polite complaints" },
    ],
  },

  /* ============ E9 Kaoyan English ============ */
  {
    id: "k1", code: "KY1", moduleId: "m9", difficulty: 3, hours: 9, prereq: ["v2", "s1"], practice: "cloze",
    nExamples: 5, nExercises: 6,
    title: { zh: "完形填空", en: "Cloze Test" },
    summary: { zh: "20 空:靠上下文逻辑、搭配与连接词选词,而非孤立背单词。", en: "20 blanks: choose by context, collocation and connectors — not isolated vocab." },
    objectives: [
      { zh: "从上下文与逻辑关系推断答案", en: "Infer answers from context and logic" },
      { zh: "掌握高频连接词与转折信号", en: "Master frequent connectors and signals" },
      { zh: "利用固定搭配与词义辨析排除", en: "Eliminate via collocation and word sense" },
      { zh: "控制完形做题时间(约 15 分钟)", en: "Time the cloze section (~15 min)" },
    ],
    outline: [
      { zh: "完形题型与评分", en: "Cloze format and scoring" },
      { zh: "首句定基调,通读全篇", en: "First sentence sets tone; read the whole" },
      { zh: "逻辑关系:因果、转折、并列", en: "Logic: cause, contrast, addition" },
      { zh: "近义词辨析与搭配", en: "Synonym discrimination and collocation" },
      { zh: "真题实练与复盘", en: "Past-paper drills and review" },
    ],
  },
  {
    id: "k5", code: "KY5", moduleId: "m9", difficulty: 3, hours: 3, prereq: ["k1"], practice: "clozeworkfree",
    nExamples: 1, nExercises: 20,
    title: { zh: "完形填空真题:无工作的未来", en: "Cloze in Practice: A Future Without Work" },
    summary: { zh: "一篇考研风格完形真题精讲:20 空全文中英对照,逐空讲清「为什么选它、为什么排除其他」。", en: "A close walk-through of one Kaoyan-style cloze: full bilingual text with all 20 blanks, each explained — why the key, why not the rest." },
    objectives: [
      { zh: "在真实语篇中运用完形四步:通读→抓逻辑→看搭配→排干扰", en: "Apply the four-step cloze method in a real passage" },
      { zh: "识别转折、举证、对比等连接信号(warning / Indeed / but…)", en: "Read connectors: contrast, evidence, comparison" },
      { zh: "用固定搭配与语义辨析排除干扰项", en: "Eliminate distractors via collocation and word sense" },
      { zh: "对照译文,梳理「无工作的未来」全文论证脉络", en: "Follow the whole argument through the parallel translation" },
    ],
    outline: [
      { zh: "全文速览与主旨脉络", en: "Overview and line of argument" },
      { zh: "全文中英对照(已填入答案)", en: "Full text with parallel translation (answers filled)" },
      { zh: "20 空逐题解析:为什么选它", en: "All 20 blanks: why the key is right" },
      { zh: "干扰项为什么错", en: "Why each distractor fails" },
      { zh: "答案速览与自测", en: "Answer key and self-test" },
    ],
  },
  {
    id: "k2", code: "KY2", moduleId: "m9", difficulty: 3, hours: 12, prereq: ["r2", "r3"], practice: "kyreading",
    nExamples: 5, nExercises: 6,
    title: { zh: "阅读理解与新题型", en: "Reading & New Question Types" },
    summary: { zh: "Part A 四选一 + Part B 七选五/排序/小标题,得阅读者得考研。", en: "Part A multiple choice + Part B (gapped text, ordering, headings) — reading wins the exam." },
    objectives: [
      { zh: "掌握主旨、细节、推断、态度、词义五类题", en: "Handle main idea, detail, inference, attitude, vocab" },
      { zh: "定位关键句并排除干扰项", en: "Locate key sentences and rule out distractors" },
      { zh: "攻克新题型:七选五与段落排序", en: "Crack gapped text and paragraph ordering" },
      { zh: "分配阅读四篇的时间", en: "Budget time across four passages" },
    ],
    outline: [
      { zh: "Part A 五大题型解法", en: "Five Part-A question types" },
      { zh: "干扰项特征与排除", en: "Distractor patterns and elimination" },
      { zh: "Part B 七选五(选句填空)", en: "Part B: gapped text" },
      { zh: "Part B 排序与小标题", en: "Part B: ordering and headings" },
      { zh: "真题精读与错题归因", en: "Close reading and error analysis" },
    ],
  },
  {
    id: "k3", code: "KY3", moduleId: "m9", difficulty: 3, hours: 9, prereq: ["s1", "s4"], practice: "translation",
    nExamples: 5, nExercises: 6,
    title: { zh: "英译汉翻译", en: "English-Chinese Translation" },
    summary: { zh: "长难句拆分、语序调整、词义引申——把英文准确译成通顺中文。", en: "Split long sentences, reorder, extend meaning — render English into fluent Chinese." },
    objectives: [
      { zh: "拆分长难句的主干与修饰", en: "Split main clause from modifiers" },
      { zh: "处理定语从句与被动语态的译法", en: "Translate relative clauses and passives" },
      { zh: "调整语序符合中文表达", en: "Reorder to fit Chinese usage" },
      { zh: "按评分点逐句得分", en: "Score by translation points" },
    ],
    outline: [
      { zh: "翻译题型与评分点", en: "Translation format and scoring points" },
      { zh: "长难句结构分析", en: "Parsing complex sentences" },
      { zh: "定语从句的前置与后置", en: "Relative clauses: pre- vs post-positioning" },
      { zh: "被动、名词化与词义引申", en: "Passive, nominalization, meaning extension" },
      { zh: "真题逐句精译", en: "Sentence-by-sentence practice" },
    ],
  },
  {
    id: "k4", code: "KY4", moduleId: "m9", difficulty: 3, hours: 10, prereq: ["w2", "w3"], practice: "kywriting",
    nExamples: 5, nExercises: 6,
    title: { zh: "小作文与大作文", en: "Writing: Letter & Essay" },
    summary: { zh: "应用文(书信/通知)+ 图表/图画作文,套路清晰、语言得体。", en: "Practical writing (letters/notices) + chart/picture essay — clear templates, appropriate tone." },
    objectives: [
      { zh: "掌握常见应用文格式与套语", en: "Master formats and set phrases for letters" },
      { zh: "描述图表/图画并展开论证", en: "Describe charts/pictures and argue" },
      { zh: "积累可复用的高分句型", en: "Build reusable high-score sentence patterns" },
      { zh: "在 40 分钟内完成两篇", en: "Finish both essays within 40 minutes" },
    ],
    outline: [
      { zh: "小作文:书信、通知、备忘", en: "Short: letters, notices, memos" },
      { zh: "大作文:图画/图表三段式", en: "Long: three-paragraph picture/chart essay" },
      { zh: "开头、主体、结尾模板", en: "Intro, body, conclusion templates" },
      { zh: "高级句型与连接手段", en: "Advanced patterns and cohesion" },
      { zh: "真题范文与仿写", en: "Model essays and imitation" },
    ],
  },

  /* ============ E10 Fables & Short Stories ============ */
  { id: "a1", code: "FB1", moduleId: "m10", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "《伊索寓言》选读", en: "Aesop's Fables" },
    summary: { zh: "《龟兔赛跑》与《狼来了》:短小寓言,寓意深长——练概括与推断。", en: "The Tortoise and the Hare and The Boy Who Cried Wolf — tiny tales, big morals." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },
  { id: "a2", code: "FB2", moduleId: "m10", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "麦琪的礼物", en: "The Gift of the Magi" },
    summary: { zh: "欧·亨利式反转:一对穷夫妻的圣诞礼物,读懂反讽与主题。", en: "O. Henry's twist: a poor couple's Christmas gifts — irony and theme." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },
  { id: "a3", code: "FB3", moduleId: "m10", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "快乐王子", en: "The Happy Prince" },
    summary: { zh: "王尔德的童话:雕像与燕子的牺牲,读懂象征与情感。", en: "Wilde's tale of a statue and a swallow — symbolism and feeling." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },
  { id: "a4", code: "FB4", moduleId: "m10", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "一小时的故事", en: "The Story of an Hour" },
    summary: { zh: "凯特·肖邦一小时里的心理转折:训练细读与推断。", en: "Chopin's hour-long turn of feeling — close reading and inference." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },
  { id: "a5", code: "FB5", moduleId: "m10", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "项链", en: "The Necklace" },
    summary: { zh: "莫泊桑的经典反转:一条借来的项链改变一生。", en: "Maupassant's famous twist: a borrowed necklace changes a life." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },
  { id: "a6", code: "FB6", moduleId: "m10", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "泄密的心", en: "The Tell-Tale Heart" },
    summary: { zh: "爱伦·坡的哥特独白:紧张语气与不可靠叙述者。", en: "Poe's gothic monologue — tension and an unreliable narrator." },
    objectives: RC_OBJ(RC_OBJ_FABLE), outline: RC_OUTLINE },

  /* ============ E11 Classic Novels ============ */
  { id: "b1", code: "NV1", moduleId: "m11", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "傲慢与偏见(开篇)", en: "Pride and Prejudice (Opening)" },
    summary: { zh: "最著名的开场白之一:反讽的第一句,读懂语气与人物。", en: "One of the most famous openings — irony from the very first line." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },
  { id: "b2", code: "NV2", moduleId: "m11", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "圣诞颂歌", en: "A Christmas Carol" },
    summary: { zh: "狄更斯笔下的斯克鲁奇:吝啬鬼的形象与转变的伏笔。", en: "Dickens's Scrooge — a miser's portrait and the seeds of change." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },
  { id: "b3", code: "NV3", moduleId: "m11", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "汤姆·索亚历险记(刷墙)", en: "Tom Sawyer (Whitewashing the Fence)" },
    summary: { zh: "马克·吐温的刷墙妙计:幽默与对人性的观察。", en: "Twain's whitewashing trick — humor and human nature." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },
  { id: "b4", code: "NV4", moduleId: "m11", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "爱丽丝漫游奇境(掉进兔子洞)", en: "Alice in Wonderland (Down the Rabbit-Hole)" },
    summary: { zh: "跟着爱丽丝掉进兔子洞:荒诞逻辑与好奇心。", en: "Down the rabbit-hole with Alice — nonsense logic and curiosity." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },
  { id: "b5", code: "NV5", moduleId: "m11", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "小妇人(开篇)", en: "Little Women (Opening)" },
    summary: { zh: "四姐妹的圣诞对话:人物性格与家庭主题。", en: "The four sisters at Christmas — character and family." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },
  { id: "b6", code: "NV6", moduleId: "m11", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "金银岛(老海盗)", en: "Treasure Island (The Old Sea-Dog)" },
    summary: { zh: "客栈里的老海盗:悬念铺陈与冒险开场。", en: "The old sea-dog at the inn — suspense and adventure." },
    objectives: RC_OBJ(RC_OBJ_NOVEL), outline: RC_OUTLINE },

  /* ============ E12 Mystery, Sci-Fi & Gothic ============ */
  { id: "c1", code: "MY1", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "福尔摩斯:斑点带子案", en: "Sherlock Holmes: The Speckled Band" },
    summary: { zh: "福尔摩斯的推理:从细节到结论,练侦探式阅读。", en: "Holmes's deduction — reading like a detective, from detail to conclusion." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },
  { id: "c2", code: "MY2", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "弗兰肯斯坦(造物苏醒)", en: "Frankenstein (The Creature Awakes)" },
    summary: { zh: "造物者与怪物:科学、责任与恐惧的经典一幕。", en: "Creator and creature — science, responsibility and dread." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },
  { id: "c3", code: "MY3", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "时间机器", en: "The Time Machine" },
    summary: { zh: "威尔斯的科幻开山:时间旅行的设定与悬念。", en: "Wells's founding sci-fi — the premise of time travel and its suspense." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },
  { id: "c4", code: "MY4", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "德拉库拉(哈克的日记)", en: "Dracula (Harker's Journal)" },
    summary: { zh: "哈克抵达城堡:书信体叙述与哥特氛围。", en: "Harker reaches the castle — epistolary form and gothic mood." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },
  { id: "c5", code: "MY5", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "沉睡谷传奇", en: "The Legend of Sleepy Hollow" },
    summary: { zh: "欧文的美国哥特:无头骑士的传说与氛围渲染。", en: "Irving's American gothic — the Headless Horseman and atmosphere." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },
  { id: "c6", code: "MY6", moduleId: "m12", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "黄色墙纸", en: "The Yellow Wallpaper" },
    summary: { zh: "吉尔曼的心理惊悚:不可靠叙述与象征,极练推断。", en: "Gilman's psychological chiller — unreliable narration and symbol." },
    objectives: RC_OBJ(RC_OBJ_MYST), outline: RC_OUTLINE },

  /* ============ E13 Speeches, Essays & Nonfiction ============ */
  { id: "d1", code: "NF1", moduleId: "m13", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "葛底斯堡演说", en: "The Gettysburg Address" },
    summary: { zh: "林肯 272 词的演讲:结构、修辞与核心论点。", en: "Lincoln's 272-word speech — structure, rhetoric and its core claim." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },
  { id: "d2", code: "NF2", moduleId: "m13", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "瓦尔登湖(节选)", en: "Walden (Excerpt)" },
    summary: { zh: "梭罗为何入林而居:散文的论点与意象。", en: "Why Thoreau went to the woods — argument and imagery in the essay." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },
  { id: "d3", code: "NF3", moduleId: "m13", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "论自我", en: "Self-Reliance" },
    summary: { zh: "爱默生的名篇:自立的主张与格言式句子。", en: "Emerson's essay — the case for self-reliance and its aphorisms." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },
  { id: "d4", code: "NF4", moduleId: "m13", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "弗雷德里克·道格拉斯自述", en: "Narrative of Frederick Douglass" },
    summary: { zh: "道格拉斯的亲历叙述:识字如何点燃自由的渴望。", en: "Douglass's firsthand account — how literacy lit the desire for freedom." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },
  { id: "d5", code: "NF5", moduleId: "m13", difficulty: 2, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "环球七十二天(内莉·布莱)", en: "Around the World in 72 Days (Nellie Bly)" },
    summary: { zh: "内莉·布莱的先驱旅行报道:真实新闻叙事的读法。", en: "Nellie Bly's pioneering travel reporting — reading real journalism." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },
  { id: "d6", code: "NF6", moduleId: "m13", difficulty: 3, hours: 2, prereq: [], practice: null, nExamples: 1, nExercises: 5,
    title: { zh: "贝格尔号航海记", en: "The Voyage of the Beagle" },
    summary: { zh: "达尔文的观察笔记:科学散文里的描写与推理。", en: "Darwin's field notes — description and reasoning in science writing." },
    objectives: RC_OBJ(RC_OBJ_NONFIC), outline: RC_OUTLINE },

  /* ============ E14 News & Real Events (cloze bank) ============ */
  { id: "g1", code: "NE1", moduleId: "m14", difficulty: 2, hours: 2, prereq: [], practice: "g1", nExamples: 0, nExercises: 30,
    title: { zh: "英国:机构 · 地标 · 历史", en: "Britain: Institutions & History" },
    summary: { zh: "议会、王室、NHS、BBC 与地标:真实话题里的选词填空。", en: "Parliament, the monarchy, the NHS, the BBC and landmarks — cloze on real UK topics." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },
  { id: "g2", code: "NE2", moduleId: "m14", difficulty: 2, hours: 2, prereq: [], practice: "g2", nExamples: 0, nExercises: 30,
    title: { zh: "美国:机构 · 地标 · 历史", en: "The United States: Institutions & History" },
    summary: { zh: "宪法、国会、总统与国家公园:真实话题里的选词填空。", en: "The Constitution, Congress, presidents and national parks — cloze on real US topics." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },
  { id: "g3", code: "NE3", moduleId: "m14", difficulty: 3, hours: 2, prereq: [], practice: "g3", nExamples: 0, nExercises: 30,
    title: { zh: "科技里程碑", en: "Science & Technology" },
    summary: { zh: "航天、计算机、互联网与医学:真实科技话题填空。", en: "Space, computing, the internet and medicine — cloze on real science and tech." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },
  { id: "g4", code: "NE4", moduleId: "m14", difficulty: 2, hours: 2, prereq: [], practice: "g4", nExamples: 0, nExercises: 30,
    title: { zh: "环境与气候", en: "Environment & Climate" },
    summary: { zh: "气候变化、可再生能源与生态保护:真实话题填空。", en: "Climate change, renewable energy and conservation — cloze on real topics." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },
  { id: "g5", code: "NE5", moduleId: "m14", difficulty: 3, hours: 2, prereq: [], practice: "g5", nExamples: 0, nExercises: 30,
    title: { zh: "商业与经济", en: "Business & Economy" },
    summary: { zh: "公司、贸易、市场与经济概念:真实话题里的选词填空。", en: "Companies, trade, markets and economic ideas — cloze on real topics." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },
  { id: "g6", code: "NE6", moduleId: "m14", difficulty: 2, hours: 2, prereq: [], practice: "g6", nExamples: 0, nExercises: 30,
    title: { zh: "体育与文化", en: "Sport & Culture" },
    summary: { zh: "奥运、足球、音乐、电影与节庆:真实话题里的选词填空。", en: "The Olympics, football, music, film and festivals — cloze on real culture." },
    objectives: BK_OBJ(BK_OBJ_NEWS), outline: BK_OUTLINE },

  /* ============ E15 Grammar in Context (gap-fill bank) ============ */
  { id: "h1", code: "GR1", moduleId: "m15", difficulty: 2, hours: 2, prereq: [], practice: "h1", nExamples: 0, nExercises: 30,
    title: { zh: "动词时态与体", en: "Verb Tenses & Aspect" },
    summary: { zh: "现在、过去、完成、将来:选出正确的时态形式。", en: "Present, past, perfect, future — choose the correct tense form." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },
  { id: "h2", code: "GR2", moduleId: "m15", difficulty: 2, hours: 2, prereq: [], practice: "h2", nExamples: 0, nExercises: 30,
    title: { zh: "冠词 · 限定词 · 量词", en: "Articles, Determiners & Quantifiers" },
    summary: { zh: "a/an/the/零冠词与 some/many/few:选对限定词。", en: "a/an/the/zero and some/many/few — pick the right determiner." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },
  { id: "h3", code: "GR3", moduleId: "m15", difficulty: 2, hours: 2, prereq: [], practice: "h3", nExamples: 0, nExercises: 30,
    title: { zh: "介词", en: "Prepositions" },
    summary: { zh: "时间、地点、方向与固定介词搭配。", en: "Time, place, movement and dependent prepositions." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },
  { id: "h4", code: "GR4", moduleId: "m15", difficulty: 3, hours: 2, prereq: [], practice: "h4", nExamples: 0, nExercises: 30,
    title: { zh: "连接词与语篇标记", en: "Connectors & Discourse Markers" },
    summary: { zh: "however/therefore/although…:按逻辑选连接词。", en: "however/therefore/although… — choose the linker by logic." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },
  { id: "h5", code: "GR5", moduleId: "m15", difficulty: 3, hours: 2, prereq: [], practice: "h5", nExamples: 0, nExercises: 30,
    title: { zh: "非谓语与情态", en: "Non-finite Verbs & Modals" },
    summary: { zh: "不定式/动名词/分词与情态动词的选用。", en: "Infinitive/gerund/participle and modal verbs." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },
  { id: "h6", code: "GR6", moduleId: "m15", difficulty: 3, hours: 2, prereq: [], practice: "h6", nExamples: 0, nExercises: 30,
    title: { zh: "定语从句 · 条件句 · 被动", en: "Relative Clauses, Conditionals & Passive" },
    summary: { zh: "who/which、if 条件句与被动语态。", en: "who/which, if-conditionals and the passive." },
    objectives: BK_OBJ(BK_OBJ_GRAM), outline: BK_OUTLINE },

  /* ============ E16 Vocabulary & Collocation (word-choice bank) ============ */
  { id: "j1", code: "VC1", moduleId: "m16", difficulty: 2, hours: 2, prereq: [], practice: "j1", nExamples: 0, nExercises: 30,
    title: { zh: "动词 + 名词搭配", en: "Verb–Noun Collocations" },
    summary: { zh: "make/do/take/have/pay + 名词:选对动词。", en: "make/do/take/have/pay + noun — choose the right verb." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
  { id: "j2", code: "VC2", moduleId: "m16", difficulty: 3, hours: 2, prereq: [], practice: "j2", nExamples: 0, nExercises: 30,
    title: { zh: "形容词与副词搭配", en: "Adjective & Adverb Collocations" },
    summary: { zh: "heavy rain、strongly agree…:选对搭配词。", en: "heavy rain, strongly agree… — pick the right collocate." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
  { id: "j3", code: "VC3", moduleId: "m16", difficulty: 3, hours: 2, prereq: [], practice: "j3", nExamples: 0, nExercises: 30,
    title: { zh: "短语动词", en: "Phrasal Verbs" },
    summary: { zh: "take off、put off、look into…:选对短语动词。", en: "take off, put off, look into… — choose the right phrasal verb." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
  { id: "j4", code: "VC4", moduleId: "m16", difficulty: 3, hours: 2, prereq: [], practice: "j4", nExamples: 0, nExercises: 30,
    title: { zh: "易混词辨析", en: "Confusable Words" },
    summary: { zh: "affect/effect、rise/raise…:选对易混词。", en: "affect/effect, rise/raise… — pick the right one." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
  { id: "j5", code: "VC5", moduleId: "m16", difficulty: 2, hours: 2, prereq: [], practice: "j5", nExamples: 0, nExercises: 30,
    title: { zh: "固定介词搭配", en: "Fixed Phrases & Dependent Prepositions" },
    summary: { zh: "depend on、interested in…:选对介词。", en: "depend on, interested in… — choose the right preposition." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
  { id: "j6", code: "VC6", moduleId: "m16", difficulty: 3, hours: 2, prereq: [], practice: "j6", nExamples: 0, nExercises: 30,
    title: { zh: "学术用词与衔接", en: "Academic Word Choice & Linking" },
    summary: { zh: "正式用词与论证衔接:选更得体、更精确的词。", en: "Formal word choice and linking — pick the more precise, appropriate word." },
    objectives: BK_OBJ(BK_OBJ_VOCAB), outline: BK_OUTLINE },
];

const TOTAL_HOURS = CHAPTERS.reduce((s, c) => s + c.hours, 0);
const TOTAL_EXAMPLES = CHAPTERS.reduce((s, c) => s + c.nExamples, 0);

window.MODULES = MODULES;
window.CHAPTERS = CHAPTERS;
window.TOTAL_HOURS = TOTAL_HOURS;
window.TOTAL_EXAMPLES = TOTAL_EXAMPLES;
